config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  #get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  resources :restaurants, only: [ :new, :create ] do
    resources :restaurant_operating_hours, only: [ :index, :new, :create ]
    resources :tags, only: [ :new, :create ]
    get 'exclude_tag', to: 'tags#exclude'
    delete 'destroy_tag', to: 'tags#destroy'

    resources :dishes, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      post 'deactivate', on: :member
      post 'activate', on: :member
      resources :servings, only: [ :new, :create, :edit, :update ] do 
        get 'history', to: 'servings#history'
      end
      get 'new_tag_assignment', to: 'tags#new_assignment'
      post 'assign_tag', to: 'tags#assign'
      get 'remove_tag_assignment', to: 'tags#remove_assignment'
      delete 'unassign_tag', to: 'tags#unassign'
    end

    resources :beverages, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      post 'deactivate', on: :member
      post 'activate', on: :member
      resources :servings, only: [ :new, :create, :edit, :update ] do
        get 'history', to: 'servings#history'
      end
    end

    get '/menu_items_search', to: 'menu_search#index'

    resources :staff_members, only: [ :index, :new, :create ]

    resources :item_option_sets, only: [ :show, :new, :create ] do
      get 'new_dish', to: 'item_option_sets#new_dish'
      post 'add_dish', to: 'item_option_sets#add_dish'
      get 'new_beverage', to: 'item_option_sets#new_beverage'
      post 'add_beverage', to: 'item_option_sets#add_beverage'
      get 'remove_item', to: 'item_option_sets#remove_item'
      delete 'delete_item', to: 'item_option_sets#delete_item'
    end

    resources :discounts, only: [ :index, :new, :create, :show ] do
      get 'new_dish_serving', to: 'discounts#new_dish_serving'
      get 'new_beverage_serving', to: 'discounts#new_beverage_serving'
      post 'assign_serving', to: 'discounts#assign'
    end

    post 'order_add_item', to: 'orders#add_item'
    get 'new_order', to: 'orders#new'
    post 'orders', to: 'orders#create'
    get 'orders', to: 'orders#index'
    resources :orders, only: [ :show ]
  end

  get '/check_order', to: 'check_orders#check_order_form', as: 'check_order_form'
  get '/check_order/order', to: 'check_orders#show', as: 'check_order'

  namespace :api, :defaults => { :format => 'json' } do
    namespace :v1 do
      get '/orders', to: 'orders#index'
      get '/order', to: 'orders#show'
      post '/order/prepare', to: 'orders#prepare'
      post '/order/mark_ready', to: 'orders#mark_ready'
      post '/order/deliver', to: 'orders#deliver'
      post '/order/cancel', to: 'orders#cancel'
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :restaurant
  has_many :dish_tags, dependent: :destroy
  has_many :dishes, through: :dish_tags

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < UserController
  before_action :get_restaurant
  def new
    @tag = Tag.new
  end

  def create
    tag_name = params[:tag][:name]
    @tag = Tag.new(name: tag_name, restaurant: @restaurant)

    if @tag.save
      redirect_to restaurant_dishes_path(@restaurant), notice: 'Tag criada com sucesso!'
    else
      flash.now[:alert] = 'Ops! :( Erro ao criar a Tag'
      render 'new', status: :unprocessable_entity
    end
  end

  def exclude
    @tags = @restaurant.tags
  end

  def destroy
    tag_id = params[:tag_id]
    @tag = Tag.find_by(id: tag_id)

    if @tag.destroy
      redirect_to restaurant_dishes_path(@restaurant), notice: 'Tag excluída com sucesso!'
    else
      flash.now[:alert] = 'Ops! :( Erro ao excluir a Tag'
      render 'exclude', status: :unprocessable_entity
    end
  end

  def new_assignment
    dish_id = params[:dish_id]
    @dish = Dish.find_by(id: dish_id)
    restaurant_tags = @restaurant.tags
    dish_tags = @dish.tags

    @tags = restaurant_tags - dish_tags
  end

  def assign
    dish_id = params[:dish_id]
    tag_id = params[:tag_id]
    @dish = Dish.find_by(id: dish_id)
    @tag = Tag.find_by(id: tag_id)

    verify_tag_ownership
    return if performed?

    dish_tag = DishTag.new(dish_id: @dish.id, tag_id: @tag.id)

    if dish_tag && dish_tag.save
      redirect_to restaurant_dish_path(@restaurant, @dish), notice: 'Característica adicionada com sucesso!'
    else
      @tags = @restaurant.tags
      flash.now[:alert] = 'Ops! :( Erro ao adicionar característica. Verifique se o prato já não possui essa característica'
      render 'new_assignment', status: :unprocessable_entity
    end
  end

  def remove_assignment
    dish_id = params[:dish_id]
    @dish = Dish.find_by(id: dish_id)
    @tags = @dish.tags
  end

  def unassign
    dish_id = params[:dish_id]
    tag_id = params[:tag_id]
    @dish = Dish.find_by(id: dish_id)
    @tag = Tag.find_by(id: tag_id)

    verify_tag_ownership
    return if performed?

    dish_tag = DishTag.find_by(dish_id: @dish.id, tag_id: @tag.id)
    return redirect_to root_path, alert: 'Esta Característica não está associada a este prato' if dish_tag.nil?

    if dish_tag.delete
      redirect_to restaurant_dish_path(@restaurant, @dish), notice: 'Característica removida com sucesso!'
    else
      @tags = @dish.tags
      flash.now[:alert] = 'Ops! :( Erro ao remover característica'
      render 'remove_assignment', status: :unprocessable_entity
    end
  end

  private
  def get_restaurant
    restaurant_id = params[:restaurant_id]
    @restaurant = Restaurant.find_by(id: restaurant_id)

    redirect_to root_path, alert: 'Ops, você não tem acesso a este restaurante' if @restaurant.id != current_user.restaurant.id
  end
  
  def verify_tag_ownership
    if @tag.nil? || @dish.nil?
      redirect_to root_path, alert: 'Prato ou Caracaterística não encontrado(s)'
    elsif @tag.restaurant != @restaurant
      redirect_to root_path, alert: 'Esta característica não pertence ao seu restaurante'
    elsif @dish.restaurant != @restaurant
      redirect_to root_path, alert: 'Este prato não pertence ao seu restaurante'
    end
  end
end

app/views/tags/exclude.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Excluir uma Tag</h2>

<%= form_with(url: restaurant_destroy_tag_path(@restaurant.id), method: :delete,  class: 'form') do |f| %>
    <div class="input_container">
        <%= f.label :tag_id, 'Escolha uma Tag para excluir', class: 'input_label' %>
        <%= f.collection_select :tag_id, @tags, :id, :name %>
    </div>

    <%= f.submit 'Excluir Tag', class: 'form_button' %>
<% end %>

app/views/tags/new.html.erb
<h2>Cadastrar Tag</h2>

<%= form_with(model: [@restaurant, @tag], class: 'form') do |f| %>
    <div class="input_container">
        <%= f.label :name, class: 'input_label' %>
        <%= f.text_field :name, auto_focus: true, class: 'input' %>
    </div>

    <%= f.submit class: 'form_button'%>
<% end %>

app/views/tags/new_assignment.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Adicionar Característica - <%= @dish.name %></h2>

<% if @tags.empty? %>
    <p class="mt-10">Não há Tags disponíveis ou todas Tags já foram assignadas a este prato</p>
<% else %>
    <%= form_with(url: restaurant_dish_assign_tag_path(@restaurant, @dish), class: 'form') do |f| %>
        <div class="input_container">
            <%= f.label :tag_id, 'Tags Disponíveis', class: 'input_label' %>
            <%= f.collection_select :tag_id, @tags, :id, :name %>
        </div>

        <%= f.submit 'Adicionar', class: 'form_button'%>
    <% end %>
<% end %>

app/views/tags/remove_assignment.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Remover Característica</h2>

<%= form_with(url: restaurant_dish_unassign_tag_path(@restaurant, @dish), method: :delete, class: 'form') do |f| %>
    <div class="input_container">
        <%= f.label :tag_id, 'Tags Disponíveis', class: 'input_label' %>
        <%= f.collection_select :tag_id, @tags, :id, :name %>
    </div>

    <%= f.submit 'Remover', class: 'form_button'%>
<% end %>