config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  #get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  resources :restaurants, only: [ :new, :create ] do
    resources :restaurant_operating_hours, only: [ :index, :new, :create ]
    resources :tags, only: [ :new, :create ]
    get 'exclude_tag', to: 'tags#exclude'
    delete 'destroy_tag', to: 'tags#destroy'

    resources :dishes, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      post 'deactivate', on: :member
      post 'activate', on: :member
      resources :servings, only: [ :new, :create, :edit, :update ] do 
        get 'history', to: 'servings#history'
      end
      get 'new_tag_assignment', to: 'tags#new_assignment'
      post 'assign_tag', to: 'tags#assign'
      get 'remove_tag_assignment', to: 'tags#remove_assignment'
      delete 'unassign_tag', to: 'tags#unassign'
    end

    resources :beverages, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      post 'deactivate', on: :member
      post 'activate', on: :member
      resources :servings, only: [ :new, :create, :edit, :update ] do
        get 'history', to: 'servings#history'
      end
    end

    get '/menu_items_search', to: 'menu_search#index'

    resources :staff_members, only: [ :index, :new, :create ]

    resources :item_option_sets, only: [ :show, :new, :create ] do
      get 'new_dish', to: 'item_option_sets#new_dish'
      post 'add_dish', to: 'item_option_sets#add_dish'
      get 'new_beverage', to: 'item_option_sets#new_beverage'
      post 'add_beverage', to: 'item_option_sets#add_beverage'
      get 'remove_item', to: 'item_option_sets#remove_item'
      delete 'delete_item', to: 'item_option_sets#delete_item'
    end

    resources :discounts, only: [ :index, :new, :create, :show ] do
      get 'new_dish_serving', to: 'discounts#new_dish_serving'
      get 'new_beverage_serving', to: 'discounts#new_beverage_serving'
      post 'assign_serving', to: 'discounts#assign'
    end

    post 'order_add_item', to: 'orders#add_item'
    get 'new_order', to: 'orders#new'
    post 'orders', to: 'orders#create'
    get 'orders', to: 'orders#index'
    resources :orders, only: [ :show ]
  end

  get '/check_order', to: 'check_orders#check_order_form', as: 'check_order_form'
  get '/check_order/order', to: 'check_orders#show', as: 'check_order'

  namespace :api, :defaults => { :format => 'json' } do
    namespace :v1 do
      get '/orders', to: 'orders#index'
      get '/order', to: 'orders#show'
      post '/order/prepare', to: 'orders#prepare'
      post '/order/mark_ready', to: 'orders#mark_ready'
      post '/order/deliver', to: 'orders#deliver'
      post '/order/cancel', to: 'orders#cancel'
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_one_attached :picture
  belongs_to :restaurant
  has_many :servings, as: :servingable
  has_many :dish_tags
  has_many :tags, through: :dish_tags
  has_many :item_option_entries, as: :itemable

  validates :name, :description, presence: true

  enum :status, { inactive: 0, active: 1 }
end

app/controllers/dishes_controller.rb
class DishesController < UserController
  before_action :get_restaurant
  def index
    filter = params[:filter]

    @dishes = Dish.where(restaurant: @restaurant)

    filtered_tag = Tag.find_by(name: filter) if filter
    if filter && filtered_tag
      @dishes = Tag.find_by(name: filter).dishes
    elsif filter
      redirect_to restaurant_dishes_path(@restaurant), alert: 'Ops! :( Tag inválida'
    end
  end

  def show
    dish_id = params[:id]
    found_dish = Dish.find_by(id: dish_id)

    verify_dish_owner(found_dish)
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = @restaurant.dishes.create(get_dish_params)

    if @dish.persisted?
      redirect_to restaurant_dish_path(@restaurant, @dish), notice: 'Prato criado com sucesso'
    else
      flash.now[:alert] = "Erro ao criar o prato. #{@dish.errors.full_messages.to_s}"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    dish_id = params[:id]
    found_dish = Dish.find_by(id: dish_id)

    verify_dish_owner(found_dish)
  end

  def update
    dish_id = params[:id]
    found_dish = Dish.find_by(id: dish_id)

    verify_dish_owner(found_dish)
    return if performed?

    if @dish.update(get_dish_params)
      redirect_to restaurant_dish_path(@restaurant, @dish), notice: 'Prato alterado com sucesso'
    else
      flash.now[:alert] = "Erro ao alterar o prato. #{@dish.errors.full_messages.to_s}"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    dish_id = params[:id]
    found_dish = Dish.find_by(id: dish_id)

    verify_dish_owner(found_dish)
    return if performed?

    if @dish.destroy
      redirect_to restaurant_dishes_path, notice: "Prato deletado com sucesso!"
    else
      flash.now[:alert] = "Não foi possível deletar o Prato"
      render 'show', status: :unprocessable_entity
    end
  end

  def deactivate
    dish_id = params[:id]
    found_dish = Dish.find_by(id: dish_id)
    
    verify_dish_owner(found_dish)
    return if performed?

    if @dish.active? && @dish.inactive!
      flash[:notice] = 'Sucesso! Prato desativado'
      redirect_to restaurant_dish_path(@restaurant, @dish)
    else
      flash.now[:notice] = 'Ocorreu um erro ao desativar o Prato'
      render 'show', status: :unprocessable_entity
    end
  end

  def activate
    dish_id = params[:id]
    found_dish = Dish.find_by(id: dish_id)

    verify_dish_owner(found_dish)
    return if performed?

    if @dish.inactive? && @dish.active!
      flash[:notice] = 'Sucesso! Prato ativado'
      redirect_to restaurant_dish_path(@restaurant, @dish)
    else
      flash.now[:notice] = 'Ocorreu um erro ao ativar o Prato'
      render 'show', status: :unprocessable_entity
    end
  end

  private
  def get_restaurant
    restaurant_id = params[:restaurant_id]
    @restaurant = Restaurant.find_by(id: restaurant_id)
    return redirect_to root_path, alert: 'Você não tem acesso a este restaurante' if @restaurant.id != current_user.restaurant.id
  end

  def get_dish_params
    params.require(:dish).permit(:name, :description, :calories, :picture)
  end

  def verify_dish_owner(found_dish)
    if found_dish.nil? 
      redirect_to root_path, alert: 'Ops! Prato não encontrado'
    end

    if found_dish.restaurant.id != @restaurant.id
      redirect_to root_path, alert: 'Ops! Você não tem acesso a pratos que não são do seu restaurante'
    end

    @dish = found_dish
  end
end

app/views/dishes/_form.html.erb
<%= form_with model: [@restaurant, @dish], class: 'form' do |f| %>
    <div class="input_container">
        <%= f.label :name, class: 'input_label' %>
        <%= f.text_field :name, class: 'input' %>
    </div>

    <div class="input_container">
        <%= f.label :description, class: 'input_label' %>
        <%= f.text_area :description, class: 'input' %>
    </div>

    <div class="input_container">
        <%= f.label :calories, 'Calorias (não obrigatório)', class: 'input_label' %>
        <%= f.number_field :calories, min: 0, step: 1, class: 'input' %>
    </div>

    <div class="input_container">
        <%= f.label :picture, class: 'input_label' %>
        <%= f.file_field :picture %>
    </div>

    <%= f.submit class:'form_button' %>
<% end %>

app/views/dishes/edit.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Alterar Prato</h2>

<%= render 'form' %>

app/views/dishes/index.html.erb
<div class="flex justify-between items-center">
    <h2>Pratos do Meu Restaurante</h2>
    <%= link_to '+ Criar Prato', new_restaurant_dish_path(current_user.restaurant), class: 'outline_button' %>
</div>

<section id="filters" class="my-10 border-y border-projectPurple p-2 flex justify-between items-center">
    <div id="filters-container" class="flex flex-wrap gap-2 items-center">
        <span class="font-bold text-projectPurple">Filtrar:</span>

        <%= link_to 'Todos', restaurant_dishes_path(@restaurant, @dish), class: params.has_key?(:filter) ? 'outline_button rounded-3xl p-[6px]' : 'form_button rounded-3xl p-[6px] my-0' %>

        <% @restaurant.tags.each do |tag| %>
            <%= link_to tag.name, restaurant_dishes_path(@restaurant, @dish, filter: tag.name), class: params[:filter] == tag.name ? 'form_button rounded-3xl p-[6px] mt-0' : 'outline_button rounded-3xl p-[6px]' %>
        <% end %>
    </div>

    <div id="filters-controls" class="flex gap-2 min-w-fit">
        <%= link_to '+ Cadastrar Tag', new_restaurant_tag_path(@restaurant), class: 'outline_button min-w-fit max-h-fit' %>
        <%= link_to 'Remover Tags', restaurant_exclude_tag_path(@restaurant), class: 'outline_button min-w-fit max-h-fit' %>
    </div>
</section>

<% if @dishes.empty? %>
    <% if params.has_key?(:filter) %>
        <p class="">Ainda não há pratos cadastrados para este filtro.</p>
    <% else %>
        <p class="">Ainda não há pratos cadastrados para o seu restaurante.</p>
    <% end %>
<% else %>
    <ul class=" flex flex-col gap-4 list-disc marker:text-projectPurple list-inside	">
        <% @dishes.each do |dish| %>
            <%= link_to restaurant_dish_path(@restaurant.id, dish.id) do %>
                <li class="hover:cursor-pointer hover:underline hover:decoration-projectPurple  hover:decoration-2 hover:underline-offset-2 transition-transform">
                    <span class="font-bold"><%= dish.name%></span> - <%= I18n.t(dish.status) %>
                </li>
            <% end %>
        <% end %>
    </ul>
<% end %>

app/views/dishes/new.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Criar Prato</h2>

<%= render 'form' %>

app/views/dishes/show.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2><%= @dish.name%></h2>


<article class="my-10 flex flex-col max-w-5xl border-2 border-projectPurpleLighter rounded-xl p-5 relative overflow-hidden">
    <section class="flex justify-between">
        <section class="flex flex-col gap-2 w-[33%]">
            <span class="font-bold text-lg text-projectPurple"><%= Dish.human_attribute_name :status %></span>
            <p>
                <% if @dish.active? %>
                    <%= I18n.t('active') %>
                <% else %>
                    <%= I18n.t('inactive') %>
                <% end %>
            </p>

            <span class="font-bold text-lg text-projectPurple"><%= Dish.human_attribute_name :description %></span>
            <p>
                <%= @dish.description%>
            </p>

            <span class="font-bold text-lg text-projectPurple"><%= Dish.human_attribute_name :calories %></span>
            <p>
                <%= @dish.calories%>
            </p>

            <div class="flex flex-col gap-2" id="tags">
                <div class="flex gap-2 items-center">
                    <span class="font-bold text-lg text-projectPurple">Tags</span>
                    <%= link_to '+', restaurant_dish_new_tag_assignment_path(@restaurant, @dish), class: 'circle_button' %>
                    <% if @dish.tags.count > 0 %>
                        <%= link_to '-', restaurant_dish_remove_tag_assignment_path(@restaurant, @dish), class: 'circle_button' %>
                    <% end %>
                </div>

                <ul class="flex flex-wrap gap-2" id="tags-list">
                    <% @dish.tags.each do | tag |%>
                        <li class="rounded-3xl p-[6px] border border-projectPurple text-projectPurple w-fit">
                            <%= tag.name %>
                        </li>
                    <% end %>
                <ul>
            </div>
        </section>

        <picture>
            <figcaption class="font-bold text-lg text-projectPurple text-center">Foto do Prato</figcaption>
            <% if @dish.picture.present? %>
                <div class="w-60 h-60">
                    <%= image_tag @dish.picture %>
                </div>
            <% else %>
                <figcaption>Este Prato ainda não possui uma foto :(</figcaption>
            <% end %>
        </picture>

        <section class="flex flex-col gap-2 justify-start max-w-5xl items-end">
            <span class="font-bold text-lg text-projectPurple">Opções</span>
            <% if @dish.active? %>
                <%= button_to 'Desativar Prato', deactivate_restaurant_dish_path(@restaurant.id, @dish.id), method: :post, class: 'outline_button text-center w-full', form: { class: 'w-full' } %>
            <% else %>
                <%= button_to 'Ativar Prato', activate_restaurant_dish_path(@restaurant.id, @dish.id), method: :post, class: 'outline_button text-center w-full', form: { class: 'w-full' } %>
            <% end %>
            <%= link_to 'Alterar Prato', edit_restaurant_dish_path(@restaurant.id, @dish.id), class: 'outline_button w-full text-center' %>
            <%= button_to 'Remover Prato', restaurant_dish_path(@restaurant.id, @dish.id), method: :delete, class: 'outline_button w-full bg-projectRed text-projectWhite border-0', form: { class: 'w-full' } %>
        </section>
    </section>

    <hr class="-mx-5 mt-10 border border-projectPurple border-dashed" />

    <section class="flex flex-col bg-projectPaperWhite py-10 px-5 -mx-5 -mb-5 font-mono">
        <header class="flex justify-between">
            <h3 class="font-bold text-[22px] text-projectPurple">Porções:</h3>
            <%= link_to '+ Cadastrar Porção', new_restaurant_dish_serving_path(@restaurant, @dish), class: 'outline_button' %>
        </header>

        <% if @dish.servings.empty? %>
            <p class="mt-4">
                Nenhuma porção cadastrada para <span class="font-bold text-projectPurple"><%= @dish.name %></span>
            </p>
        <% else %>
            <ul class="mt-4 flex flex-col gap-4">
            <% @dish.servings.each do | serving | %>
                <li class="w-[70%] flex items-center justify-between border-l border-projectPurple">
                    <p class="ml-4">
                        <span class="font-bold"><%= serving.description%></span>
                        - <%= number_to_currency(serving.current_price, precision: 2) %>
                    </p>
                    <div class="flex gap-4">
                        <%= link_to 'Editar', edit_restaurant_dish_serving_path(@restaurant, @dish, serving), class: 'outline_button p-2' %>
                        <%= link_to 'Histórico', restaurant_dish_serving_history_path(@restaurant, @dish, serving), class: 'outline_button p-2' %>
                    </div>
                </li>
            <% end %>
            </ul>
        <% end %>
    </section>
</article>