config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  #get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  resources :restaurants, only: [ :new, :create ] do
    resources :restaurant_operating_hours, only: [ :index, :new, :create ]
    resources :tags, only: [ :new, :create ]
    get 'exclude_tag', to: 'tags#exclude'
    delete 'destroy_tag', to: 'tags#destroy'

    resources :dishes, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      post 'deactivate', on: :member
      post 'activate', on: :member
      resources :servings, only: [ :new, :create, :edit, :update ] do 
        get 'history', to: 'servings#history'
      end
      get 'new_tag_assignment', to: 'tags#new_assignment'
      post 'assign_tag', to: 'tags#assign'
      get 'remove_tag_assignment', to: 'tags#remove_assignment'
      delete 'unassign_tag', to: 'tags#unassign'
    end

    resources :beverages, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      post 'deactivate', on: :member
      post 'activate', on: :member
      resources :servings, only: [ :new, :create, :edit, :update ] do
        get 'history', to: 'servings#history'
      end
    end

    get '/menu_items_search', to: 'menu_search#index'

    resources :staff_members, only: [ :index, :new, :create ]

    resources :item_option_sets, only: [ :show, :new, :create ] do
      get 'new_dish', to: 'item_option_sets#new_dish'
      post 'add_dish', to: 'item_option_sets#add_dish'
      get 'new_beverage', to: 'item_option_sets#new_beverage'
      post 'add_beverage', to: 'item_option_sets#add_beverage'
      get 'remove_item', to: 'item_option_sets#remove_item'
      delete 'delete_item', to: 'item_option_sets#delete_item'
    end

    resources :discounts, only: [ :index, :new, :create, :show ] do
      get 'new_dish_serving', to: 'discounts#new_dish_serving'
      get 'new_beverage_serving', to: 'discounts#new_beverage_serving'
      post 'assign_serving', to: 'discounts#assign'
    end

    post 'order_add_item', to: 'orders#add_item'
    get 'new_order', to: 'orders#new'
    post 'orders', to: 'orders#create'
    get 'orders', to: 'orders#index'
    resources :orders, only: [ :show ]
  end

  get '/check_order', to: 'check_orders#check_order_form', as: 'check_order_form'
  get '/check_order/order', to: 'check_orders#show', as: 'check_order'

  namespace :api, :defaults => { :format => 'json' } do
    namespace :v1 do
      get '/orders', to: 'orders#index'
      get '/order', to: 'orders#show'
      post '/order/prepare', to: 'orders#prepare'
      post '/order/mark_ready', to: 'orders#mark_ready'
      post '/order/deliver', to: 'orders#deliver'
      post '/order/cancel', to: 'orders#cancel'
    end
  end
end

app/models/item_option_set.rb
class ItemOptionSet < ApplicationRecord
  belongs_to :restaurant
  has_many :item_option_entries

  has_many :dishes, through: :item_option_entries, source: :itemable, source_type: 'Dish'
  has_many :beverages, through: :item_option_entries, source: :itemable, source_type: 'Beverage'

  validates :end_date, presence: true, if: Proc.new { self.start_date != nil && self.start_date != '' }
  validates :start_date, presence: true, if: Proc.new { self.end_date != nil && self.end_date != '' }
  validates :end_date, comparison: { greater_than: :start_date }, if: Proc.new { self.start_date != nil && self.start_date != '' && self.end_date != nil && self.end_date != ''}

  validates :name, presence: true
  validates :name, uniqueness: { scope: :restaurant_id, message: "deve ser único para o restaurante"  }

  def active_item_option_entries
    self.item_option_entries.filter { |item_entry| item_entry.itemable.active? }
  end

  def is_seasonal?
    self.start_date.present?
  end

  def is_in_season?
    Time.zone.now > self.start_date && Time.zone.now < self.end_date
  end
end

app/controllers/item_option_sets_controller.rb
class ItemOptionSetsController < UserController
  before_action :get_restaurant

  def index
    # @item_option_sets = @restaurant.item_option_sets
  end
  
  def new
    @item_option_set = ItemOptionSet.new
  end

  def create
    item_option_set_params = params.require(:item_option_set).permit(:name, :start_date, :end_date)

    @item_option_set = @restaurant.item_option_sets.build
    @item_option_set.assign_attributes(item_option_set_params)

    if @item_option_set.save
      redirect_to root_path, notice: 'Cardápio criado com sucesso!'
    else
      flash.now[:alert] = 'Ops! :( Erro ao criar o Cardápio'
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    set_id = params[:id]
    @item_option_set = ItemOptionSet.find(set_id)

    verify_item_set_ownership
    return if performed?

    return redirect_to root_path, alert: 'Voce não tem acesso a este cardápio' if current_user.staff? && @item_option_set.is_seasonal? && !@item_option_set.is_in_season?

    @item_option_entries = @item_option_set.active_item_option_entries
  end

  def new_dish
    set_id = params[:item_option_set_id]
    @item_option_set = ItemOptionSet.find(set_id)

    verify_item_set_ownership
    return if performed?

    restaurant_dishes = @restaurant.dishes.active
    set_dishes_ids = @item_option_set.dish_ids

    @available_dishes = restaurant_dishes.reject { |dish| set_dishes_ids.include?( dish.id )}
  end

  def add_dish
    item_set_params = params[:item_option_set_id]
    dish_id = params[:dish_id]

    @dish = Dish.find(dish_id)

    verify_dish_ownership
    return if performed?

    @item_option_set = ItemOptionSet.find(item_set_params)
    @item_option_set.item_option_entries.build(itemable: @dish)

    verify_item_set_ownership
    return if performed?

    if @item_option_set.save
      redirect_to restaurant_item_option_set_path(@restaurant, @item_option_set), notice: "Prato #{@dish.name} adicionado ao Cardápio com sucesso!"
    else
      restaurant_dishes = @restaurant.dishes.active
      set_dishes_ids = @item_option_set.dish_ids

      @available_dishes = restaurant_dishes.reject { |dish| set_dishes_ids.include?( dish.id )}
      flash.now[:alert] = 'Ops! :( Erro ao adicionar o prato ao Cardápio'
      render 'new_dish', status: :unprocessable_entity
    end
  end

  def new_beverage
    set_id = params[:item_option_set_id]
    @item_option_set = ItemOptionSet.find(set_id)

    verify_item_set_ownership
    return if performed?

    restaurant_beverages = @restaurant.beverages.active
    set_beverages_ids = @item_option_set.beverage_ids

    @available_beverages = restaurant_beverages.reject { |beverage| set_beverages_ids.include?( beverage.id )}
  end

  def add_beverage
    item_set_params = params[:item_option_set_id]
    beverage_id = params[:beverage_id]

    @beverage = Beverage.find(beverage_id)
    verify_beverage_ownership
    return if performed?

    @item_option_set = ItemOptionSet.find(item_set_params)
    @item_option_set.item_option_entries.build(itemable: @beverage)

    verify_item_set_ownership
    return if performed?

    if @item_option_set.save
      redirect_to restaurant_item_option_set_path(@restaurant, @item_option_set), notice: "Bebida #{@beverage.name} adicionada ao Cardápio com sucesso!"
    else
      restaurant_beverages = @restaurant.beverages.active
      set_beverages_ids = @item_option_set.beverage_ids

      @available_beverages = restaurant_beverages.reject { |beverage| set_beverages_ids.include?( beverage.id )}
      flash.now[:alert] = 'Ops! :( Erro ao adicionar o prato ao Cardápio'
      render 'new_beverage', status: :unprocessable_entity
    end
  end

  def remove_item
    set_id = params[:item_option_set_id]
    @item_option_set = ItemOptionSet.find(set_id)

    verify_item_set_ownership
    return if performed?

    @available_items = @item_option_set.item_option_entries
  end

  def delete_item
    set_id = params[:item_option_set_id]
    item_id = params[:item_id]

    @item_option_set = ItemOptionSet.find(set_id)
    verify_item_set_ownership
    return if performed?

    @item_to_remove = ItemOptionEntry.find(item_id)
    verify_item_entry_ownership
    return if performed?

    if @item_to_remove.delete
      redirect_to restaurant_item_option_set_path(@restaurant, @item_option_set), notice: "Item #{@item_to_remove.item_name} removido do Cardápio com sucesso!"
    else
      @available_items = @item_option_set.item_option_entries
      flash.now[:alert] = 'Ops! :( Erro ao remover o item do Cardápio'
      render 'remove_item', status: :unprocessable_entity
    end
  end

  private
  def get_restaurant
    restaurant_id = params[:restaurant_id]
    @restaurant = restaurant_id ? Restaurant.find(restaurant_id) : current_user.restaurant

    redirect_to root_path, alert: 'Você não tem acesso aos cardápios deste restaurante' if @restaurant.id != current_user.restaurant.id
  end

  def verify_item_set_ownership
    redirect_to root_path, alert: "Voce não tem acesso a este Cardápio" if @item_option_set.restaurant.id != current_user.restaurant.id
  end

  def verify_dish_ownership
    redirect_to root_path, alert: "Voce não tem acesso ao Prato informado" if @dish.restaurant.id != current_user.restaurant.id
  end

  def verify_beverage_ownership
    redirect_to root_path, alert: "Voce não tem acesso a Bebida informada" if @beverage.restaurant.id != current_user.restaurant.id
  end

  def verify_item_entry_ownership
    redirect_to root_path, alert: "Voce não tem acesso ao Prato/Bebida informado(a)" if @item_to_remove.itemable.restaurant.id != current_user.restaurant.id
  end
end

app/views/item_option_sets/_index.html.erb
<div class="flex justify-between items-center">
    <h2><%= @restaurant.brand_name%> - Cardápios</h2>

    <% if current_user.owner? %>
        <%= link_to '+ Criar Cardápio', new_restaurant_item_option_set_path(@restaurant), class: 'outline_button' %>
    <% end %>
</div>


<% if @item_option_sets.empty? %>
    <p class="mt-10">Ainda não há Cardápios cadastrados para o seu restaurante.</p>
<% else %>
    <ul class="mt-10 flex flex-wrap gap-4">
    <% @item_option_sets.each do |option_set| %>
        <% if !option_set.is_seasonal? || current_user.owner? && option_set.is_seasonal? || current_user.staff? && option_set.is_seasonal? && option_set.is_in_season? %>
            <%= link_to restaurant_item_option_set_path(@restaurant, option_set) do %>
                <li class="border border-projectPurple p-8 rounded-xl hover:bg-projectPurple hover:text-projectWhite transition-all">
                    <p ><%= option_set.name %></p>
                </li>
            <% end %>
        <% end %>
    <% end %>
    </ul>
<% end %>

app/views/item_option_sets/index.html.erb
<div class="flex justify-between items-center">
    <h2>Cardápios</h2>
    <%= link_to '+ Criar Cardápio', new_restaurant_item_option_set_path, class: 'outline_button' %>
</div>


<% if @item_option_sets.empty? %>
    <p class="mt-10">Ainda não há Cardápios cadastrados para o seu restaurante.</p>
<% else %>
    <ul class="mt-10 flex flex-wrap gap-4">
    <% @item_option_sets.each do |option_set| %>
        <%= link_to restaurant_item_option_set_path(@restaurant, option_set) do %>
            <li class="border border-projectPurple p-8 rounded-xl hover:bg-projectPurple hover:text-projectWhite transition-all">
                <p ><%= option_set.name %></p>
            </li>
        <% end %>
    <% end %>
    </ul>
<% end %>

app/views/item_option_sets/new.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Novo Cardápio</h2>

<%= form_with(model: [@restaurant, @item_option_set], class: 'form') do |f| %>
    <div class="input_container">
        <%= f.label :name, class: 'input_label' %>
        <%= f.text_field :name, class: 'input' %>
    </div>

    <div class="input_container">
        <%= f.label :start_date, class: 'input_label' %>
        <%= f.date_field :start_date, class: 'input' %>
    </div>

    <div class="input_container">
        <%= f.label :end_date, class: 'input_label' %>
        <%= f.date_field :end_date, class: 'input' %>
    </div>

    <%= f.submit class: 'form_button'%>
<% end %>

app/views/item_option_sets/new_beverage.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Adicionar Bebida a <%= @item_option_set.name %></h2>

<% if @available_beverages.empty? %>
    <p class="mt-10">Não há Bebidas disponíveis ou todas Bebidas já foram assignadas a este Cardápio</p>
<% else %>
    <%= form_with(url: restaurant_item_option_set_add_beverage_path(@restaurant, @item_option_set), method: :post, class:'form') do |f| %>
        <div class="input_container">
            <%= f.label :beverage_id, 'Bebidas Disponíveis', class: 'input_label' %>
            <%= f.collection_select :beverage_id, @available_beverages, :id, :name %>
        </div>

        <%= f.submit 'Adicionar', class: 'form_button'%>
    <% end %>
<% end %>

app/views/item_option_sets/new_dish.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Adicionar Prato a <%= @item_option_set.name %></h2>

<% if @available_dishes.empty? %>
    <p class="mt-10">Não há Pratos disponíveis ou todos Pratos já foram assignados a este Cardápio</p>
<% else %>
    <%= form_with(url: restaurant_item_option_set_add_dish_path(@restaurant, @item_option_set), method: :post, class:'form') do |f| %>
        <div class="input_container">
            <%= f.label :dish_id, 'Pratos Disponíveis', class: 'input_label' %>
            <%= f.collection_select :dish_id, @available_dishes, :id, :name %>
        </div>

        <%= f.submit 'Adicionar', class: 'form_button'%>
    <% end %>
<% end %>

app/views/item_option_sets/remove_item.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<h2>Remover Item de <%= @item_option_set.name %></h2>

<% if @available_items.empty? %>
    <p class="mt-10">Não há Pratos/Bebidas neste Cardápio.</p>
<% else %>
    <%= form_with(url: restaurant_item_option_set_delete_item_path(@restaurant, @item_option_set), method: :delete, class:'form') do |f| %>
        <div class="input_container">
            <%= f.label :item_id, 'Itens Disponíveis', class: 'input_label' %>
            <%= f.collection_select :item_id, @available_items, :id, :item_name %>
        </div>

        <%= f.submit 'Remover', class: 'form_button'%>
    <% end %>
<% end %>

app/views/item_option_sets/show.html.erb
<%= link_to '< Voltar', request.referer, class: "h-fit w-fit underline decoration-2 underline-offset-8 decoration-projectPurple mb-10 font-bold" %>

<div class="flex justify-between items-center">
    <h2>Cardápio - <%= @item_option_set.name %></h2>

    <% if current_user.owner? %>
        <%= link_to 'Adicionar Prato ao Cardápio', restaurant_item_option_set_new_dish_path(@restaurant, @item_option_set), class: 'outline_button' %>
        <%= link_to 'Adicionar Bebida ao Cardápio', restaurant_item_option_set_new_beverage_path(@restaurant, @item_option_set), class: 'outline_button' %>
        <% if !@item_option_entries.empty? %>
            <%= link_to 'Remover Prato/Bebida do Cardápio', restaurant_item_option_set_remove_item_path(@restaurant, @item_option_set), class: 'outline_button' %>
        <% end %>
    <% end %>
</div>

<% if current_user.owner? && @item_option_set.is_seasonal? %>
    <p class="my-10 font-bold text-lg">
        Valido de  <span class="text-projectPurple"pan><%= l(@item_option_set.start_date) %></span>
        até 
        <span class="text-projectPurple"><%= l(@item_option_set.end_date) %></span>
    </p>
<% end %>

<section class="mt-10 flex flex-col">
    <% if @item_option_entries.empty? %>
        <p>Ainda não há nenhum prato ou bebida cadastrados neste Cardápio.</p>
    <% else %>
        <h3 class="text-projectPurple mb-5">Opções:</h3>
        <ul class="flex flex-col gap-4 bg-projectPaperWhite rounded-sm xl:max-w-[60%] p-4 border border-projectPurple">
            <% @item_option_entries.each do |item_option| %>
                <li class="font-mono flex flex-col gap-2">
                    <p class="font-bold text-projectPurple text-lg"><%= item_option.itemable.name %></p>
                    <% item_option.itemable.servings.each do |serving| %>
                        <div class="flex items-baseline">
                            <span class="ml-6"><%= serving.description %></span>
                            <span class="flex-1 border-b-2 border-projectPurple border-dotted block h-full"></span>
                            <span class="mr-6"><%= number_to_currency(serving.current_price) %></span>
                            <%= button_to 'Adicionar ao Pedido', restaurant_order_add_item_path(@restaurant, item_set_id: @item_option_set.id, item_id: serving.id), method: :post, id: dom_id(serving), class: 'outline_button p-2'%>
                        </div>
                    <% end %>
                </li>
            <% end %>
        </ul>
    <% end %>
</section>